// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.3
// source: proto/tunnel.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TunnelServiceClient is the client API for TunnelService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TunnelServiceClient interface {
	// RPC bidireccional para establecer y mantener la conexión de control
	// y para transportar datos de conexiones Firebird multiplexadas.
	// El cliente (agente junto a Firebird DB) inicia esta conexión.
	// El servidor (expuesto) puede enviar mensajes para iniciar túneles de datos.
	ConnectControl(ctx context.Context, opts ...grpc.CallOption) (TunnelService_ConnectControlClient, error)
}

type tunnelServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTunnelServiceClient(cc grpc.ClientConnInterface) TunnelServiceClient {
	return &tunnelServiceClient{cc}
}

func (c *tunnelServiceClient) ConnectControl(ctx context.Context, opts ...grpc.CallOption) (TunnelService_ConnectControlClient, error) {
	stream, err := c.cc.NewStream(ctx, &TunnelService_ServiceDesc.Streams[0], "/tunnel.TunnelService/ConnectControl", opts...)
	if err != nil {
		return nil, err
	}
	x := &tunnelServiceConnectControlClient{stream}
	return x, nil
}

type TunnelService_ConnectControlClient interface {
	Send(*Frame) error
	Recv() (*Frame, error)
	grpc.ClientStream
}

type tunnelServiceConnectControlClient struct {
	grpc.ClientStream
}

func (x *tunnelServiceConnectControlClient) Send(m *Frame) error {
	return x.ClientStream.SendMsg(m)
}

func (x *tunnelServiceConnectControlClient) Recv() (*Frame, error) {
	m := new(Frame)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TunnelServiceServer is the server API for TunnelService service.
// All implementations must embed UnimplementedTunnelServiceServer
// for forward compatibility
type TunnelServiceServer interface {
	// RPC bidireccional para establecer y mantener la conexión de control
	// y para transportar datos de conexiones Firebird multiplexadas.
	// El cliente (agente junto a Firebird DB) inicia esta conexión.
	// El servidor (expuesto) puede enviar mensajes para iniciar túneles de datos.
	ConnectControl(TunnelService_ConnectControlServer) error
	mustEmbedUnimplementedTunnelServiceServer()
}

// UnimplementedTunnelServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTunnelServiceServer struct {
}

func (UnimplementedTunnelServiceServer) ConnectControl(TunnelService_ConnectControlServer) error {
	return status.Errorf(codes.Unimplemented, "method ConnectControl not implemented")
}
func (UnimplementedTunnelServiceServer) mustEmbedUnimplementedTunnelServiceServer() {}

// UnsafeTunnelServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TunnelServiceServer will
// result in compilation errors.
type UnsafeTunnelServiceServer interface {
	mustEmbedUnimplementedTunnelServiceServer()
}

func RegisterTunnelServiceServer(s grpc.ServiceRegistrar, srv TunnelServiceServer) {
	s.RegisterService(&TunnelService_ServiceDesc, srv)
}

func _TunnelService_ConnectControl_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TunnelServiceServer).ConnectControl(&tunnelServiceConnectControlServer{stream})
}

type TunnelService_ConnectControlServer interface {
	Send(*Frame) error
	Recv() (*Frame, error)
	grpc.ServerStream
}

type tunnelServiceConnectControlServer struct {
	grpc.ServerStream
}

func (x *tunnelServiceConnectControlServer) Send(m *Frame) error {
	return x.ServerStream.SendMsg(m)
}

func (x *tunnelServiceConnectControlServer) Recv() (*Frame, error) {
	m := new(Frame)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TunnelService_ServiceDesc is the grpc.ServiceDesc for TunnelService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TunnelService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tunnel.TunnelService",
	HandlerType: (*TunnelServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ConnectControl",
			Handler:       _TunnelService_ConnectControl_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/tunnel.proto",
}
